# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.default_client_error import DefaultClientError

class TestDefaultClientError(unittest.TestCase):
    """DefaultClientError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultClientError:
        """Test DefaultClientError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultClientError`
        """
        model = DefaultClientError()
        if include_optional:
            return DefaultClientError(
                status = 'Error',
                message = 'Operation failed due to a client error',
                detail = '',
                status_code = 56
            )
        else:
            return DefaultClientError(
        )
        """

    def testDefaultClientError(self):
        """Test DefaultClientError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
