# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.cpu_query_input import CpuQueryInput

class TestCpuQueryInput(unittest.TestCase):
    """CpuQueryInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CpuQueryInput:
        """Test CpuQueryInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CpuQueryInput`
        """
        model = CpuQueryInput()
        if include_optional:
            return CpuQueryInput(
                operator = 'EQUALS',
                options = perian.models.query_options.QueryOptions(
                    limit = 56, 
                    offset = 56, 
                    order = null, 
                    lazy_loading = True, ),
                no = 56,
                cores = 56,
                threads = 56,
                speed = None
            )
        else:
            return CpuQueryInput(
        )
        """

    def testCpuQueryInput(self):
        """Test CpuQueryInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
