# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.storage_type import StorageType

class TestStorageType(unittest.TestCase):
    """StorageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageType(self):
        """Test StorageType"""
        # inst = StorageType()

if __name__ == '__main__':
    unittest.main()
