# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.default_server_error import DefaultServerError

class TestDefaultServerError(unittest.TestCase):
    """DefaultServerError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultServerError:
        """Test DefaultServerError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultServerError`
        """
        model = DefaultServerError()
        if include_optional:
            return DefaultServerError(
                status = 'Error',
                message = 'Operation failed due to a server error',
                detail = '',
                status_code = 56
            )
        else:
            return DefaultServerError(
        )
        """

    def testDefaultServerError(self):
        """Test DefaultServerError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
