# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.instance_type_view import InstanceTypeView

class TestInstanceTypeView(unittest.TestCase):
    """InstanceTypeView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceTypeView:
        """Test InstanceTypeView
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceTypeView`
        """
        model = InstanceTypeView()
        if include_optional:
            return InstanceTypeView(
                id = '',
                name = '',
                provider = perian.models.provider.Provider(
                    id = '', 
                    name = null, 
                    name_short = '', 
                    regions = [
                        perian.models.region.Region(
                            id = '', 
                            name = '', 
                            city = '', 
                            location = null, 
                            sustainable = True, 
                            status = null, 
                            zones = [
                                perian.models.zone.Zone(
                                    id = '', 
                                    name = '', 
                                    status = null, )
                                ], )
                        ], 
                    location = null, 
                    status = null, 
                    capabilities = [
                        'PricingAPI'
                        ], 
                    properties = null, ),
                region = perian.models.region.Region(
                    id = '', 
                    name = '', 
                    city = '', 
                    location = null, 
                    sustainable = True, 
                    status = null, 
                    zones = [
                        perian.models.zone.Zone(
                            id = '', 
                            name = '', 
                            status = null, )
                        ], ),
                zone = perian.models.zone.Zone(
                    id = '', 
                    name = '', 
                    status = null, ),
                type = 'Virtual',
                cpu = perian.models.cpu_data.CpuData(
                    no = 56, 
                    cores = 56, 
                    threads = 56, 
                    cpus = [
                        perian.models.cpu.Cpu(
                            threads = 56, 
                            cores = 56, 
                            speed = null, )
                        ], ),
                accelerator = perian.models.accelerator_data_view.AcceleratorDataView(
                    no = 56, 
                    memory = null, 
                    accelerator_types = [
                        perian.models.accelerator_type_view.AcceleratorTypeView(
                            name = null, 
                            display_name = '', 
                            id = '', 
                            vendor = null, 
                            memory = null, )
                        ], ),
                ram = perian.models.memory.Memory(
                    size = '0.0', 
                    unit = null, 
                    bandwidth = null, 
                    interface = null, ),
                storage = perian.models.storage_data.StorageData(
                    no = 56, 
                    size = null, 
                    included = null, 
                    storages = [
                        perian.models.storage.Storage(
                            type = null, 
                            size = null, 
                            speed = null, )
                        ], ),
                network = perian.models.network.Network(
                    inbound = null, 
                    outbound = null, ),
                price = perian.models.price_data.PriceData(
                    unit_price = '0.0', 
                    currency = null, 
                    granularity = null, 
                    provider_billing_granularity = null, ),
                availability = perian.models.availability.Availability(
                    available = True, 
                    source = null, )
            )
        else:
            return InstanceTypeView(
        )
        """

    def testInstanceTypeView(self):
        """Test InstanceTypeView"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
