# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.memory import Memory

class TestMemory(unittest.TestCase):
    """Memory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Memory:
        """Test Memory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Memory`
        """
        model = Memory()
        if include_optional:
            return Memory(
                size = '0.0',
                unit = 'Gb',
                bandwidth = perian.models.bandwidth.Bandwidth(
                    speed = '0.0', 
                    maximum = '0.0', 
                    minimum = '0.0', 
                    unit = null, 
                    sla = null, 
                    limit = null, ),
                interface = 'Hbm2'
            )
        else:
            return Memory(
        )
        """

    def testMemory(self):
        """Test Memory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
