# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.price_query_input import PriceQueryInput

class TestPriceQueryInput(unittest.TestCase):
    """PriceQueryInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceQueryInput:
        """Test PriceQueryInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceQueryInput`
        """
        model = PriceQueryInput()
        if include_optional:
            return PriceQueryInput(
                operator = 'EQUALS',
                options = perian.models.query_options.QueryOptions(
                    limit = 56, 
                    offset = 56, 
                    order = null, 
                    lazy_loading = True, ),
                unit_price = None
            )
        else:
            return PriceQueryInput(
        )
        """

    def testPriceQueryInput(self):
        """Test PriceQueryInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
