# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego_api.api.channels_api import ChannelsApi


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChannelsApi()

    def tearDown(self) -> None:
        pass

    def test_get_channels_channels_get(self) -> None:
        """Test case for get_channels_channels_get

        Retrieve Channels
        """
        pass

    def test_get_webhook_event_by_channel_channels_channel_id_webhooks_events_get(self) -> None:
        """Test case for get_webhook_event_by_channel_channels_channel_id_webhooks_events_get

        Retrieve available webhooks by channel id
        """
        pass

    def test_get_webhook_event_channels_webhooks_events_get(self) -> None:
        """Test case for get_webhook_event_channels_webhooks_events_get

        Retrieve available webhooks and corresponding channels
        """
        pass


if __name__ == '__main__':
    unittest.main()
