# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego_api.models.model_out_send import ModelOutSend

class TestModelOutSend(unittest.TestCase):
    """ModelOutSend unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelOutSend:
        """Test ModelOutSend
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelOutSend`
        """
        model = ModelOutSend()
        if include_optional:
            return ModelOutSend(
                channel = '',
                provider = '',
                swg_uids = {
                    'key' : ''
                    },
                transaction_id = ''
            )
        else:
            return ModelOutSend(
                channel = '',
                provider = '',
                swg_uids = {
                    'key' : ''
                    },
                transaction_id = '',
        )
        """

    def testModelOutSend(self):
        """Test ModelOutSend"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
