# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ListOrdering(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    NEWEST = 'newest'
    OLDEST = 'oldest'
    ALPHABETICAL_ASCENDING = 'alphabetical_ascending'
    ALPHABETICAL_DESCENDING = 'alphabetical_descending'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ListOrdering from a JSON string"""
        return cls(json.loads(json_str))


