# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.object_field_selector import ObjectFieldSelector
from openapi_server import util

from openapi_server.models.object_field_selector import ObjectFieldSelector  # noqa: E501

class EnvVarSource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, field_ref=None):  # noqa: E501
        """EnvVarSource - a model defined in OpenAPI

        :param field_ref: The field_ref of this EnvVarSource.  # noqa: E501
        :type field_ref: ObjectFieldSelector
        """
        self.openapi_types = {
            'field_ref': ObjectFieldSelector
        }

        self.attribute_map = {
            'field_ref': 'field_ref'
        }

        self._field_ref = field_ref

    @classmethod
    def from_dict(cls, dikt) -> 'EnvVarSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EnvVarSource of this EnvVarSource.  # noqa: E501
        :rtype: EnvVarSource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def field_ref(self):
        """Gets the field_ref of this EnvVarSource.


        :return: The field_ref of this EnvVarSource.
        :rtype: ObjectFieldSelector
        """
        return self._field_ref

    @field_ref.setter
    def field_ref(self, field_ref):
        """Sets the field_ref of this EnvVarSource.


        :param field_ref: The field_ref of this EnvVarSource.
        :type field_ref: ObjectFieldSelector
        """

        self._field_ref = field_ref
