'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.18

version: 0.1.18

full_version: 0.1.18

git_revision: a63f92548e6521b110be6f886a0717ed53d45f1e

release: True

'''
short_version: str = '0.1.18'
version: str = '0.1.18'
full_version: str = '0.1.18'
git_revision: str = 'a63f92548e6521b110be6f886a0717ed53d45f1e'
release: bool = True
if not release:
    version = full_version
