# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego_api.models.webhook_event_type import WebhookEventType

class TestWebhookEventType(unittest.TestCase):
    """WebhookEventType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookEventType:
        """Test WebhookEventType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookEventType`
        """
        model = WebhookEventType()
        if include_optional:
            return WebhookEventType(
                id = 0,
                channel_id = 0,
                event_type = ''
            )
        else:
            return WebhookEventType(
                id = 0,
                channel_id = 0,
                event_type = '',
        )
        """

    def testWebhookEventType(self):
        """Test WebhookEventType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
