
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-31T15:23:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7dd2d437e64dd0b20bf9cb9dbe400be10dcd9624",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
