# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego.models.response_client_user_update import ResponseClientUserUpdate

class TestResponseClientUserUpdate(unittest.TestCase):
    """ResponseClientUserUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseClientUserUpdate:
        """Test ResponseClientUserUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseClientUserUpdate`
        """
        model = ResponseClientUserUpdate()
        if include_optional:
            return ResponseClientUserUpdate(
                first_name = '0',
                last_name = '0',
                job_title = '0',
                phone_number = '0',
                is_verified = True,
                onboarded = True
            )
        else:
            return ResponseClientUserUpdate(
                is_verified = True,
                onboarded = True,
        )
        """

    def testResponseClientUserUpdate(self):
        """Test ResponseClientUserUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
