# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego.models.mbz_swg_pgsql_models_sweego_conf_joins_billing_plan_info_data import MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData

class TestMbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData(unittest.TestCase):
    """MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData:
        """Test MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData`
        """
        model = MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData()
        if include_optional:
            return MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData(
                id = 0,
                range_name = '',
                plan_name = '',
                price = 56,
                commitment = 'day',
                current_period_start_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_period_end_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                subscription_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                termination_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                active = True
            )
        else:
            return MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData(
                id = 0,
                range_name = '',
                plan_name = '',
                price = 56,
                commitment = 'day',
                current_period_start_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_period_end_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                subscription_dt = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                active = True,
        )
        """

    def testMbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData(self):
        """Test MbzSwgPgsqlModelsSweegoConfJoinsBillingPlanInfoData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
