from ralium.webpage import WebHook
from ralium._util import Any

RE_HTML_PATTERN: str

class PyHTML:
    def __init__(self, webhook: WebHook) -> None: ...

    def compile(self) -> str: ...
    def process(self, blocks: list[str]) -> list[str]: ...
    
    @staticmethod
    def locals(webhook: WebHook) -> dict[str, Any]: ...
    @staticmethod
    def get_outcome(code: str, locals: dict[str, Any]) -> list[str | None]: ...
    @staticmethod
    def get_enclosed(text: str, start: str, end: str) -> list[str]: ...