
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-31T12:20:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "353b771b59b25b2d7e29c56c9ec70387042a70a1",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
