# Generated by Django 2.2.26 on 2022-10-04 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mellon', '0007_sessionindex_transient_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionindex',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionindex',
            name='logout_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Timestamp of the last logout'),
        ),
    ]
