__all__ = (
    "SW_FORCEMINIMIZE",
    "SW_HIDE",
    "SW_MAXIMIZE",
    "SW_MINIMIZE",
    "SW_NORMAL",
    "SW_RESTORE",
    "SW_SHOW",
    "SW_SHOWDEFAULT",
    "SW_SHOWMAXIMIZED",
    "SW_SHOWMINIMIZED",
    "SW_SHOWMINNOACTIVE",
    "SW_SHOWNA",
    "SW_SHOWNOACTIVATE",
    "SW_SHOWNORMAL",
)

SW_HIDE = 0
SW_SHOWNORMAL = 1
SW_NORMAL = 1
SW_SHOWMINIMIZED = 2
SW_SHOWMAXIMIZED = 3
SW_MAXIMIZE = 3
SW_SHOWNOACTIVATE = 4
SW_SHOW = 5
SW_MINIMIZE = 6
SW_SHOWMINNOACTIVE = 7
SW_SHOWNA = 8
SW_RESTORE = 9
SW_SHOWDEFAULT = 10
SW_FORCEMINIMIZE = 11
