from lanQ_rule.common_rule import *
from lanQ_rule.model_rule import *
from lanQ_rule.prompt_rule import *

en_all = [
    common_enter_more,
    common_content_null,
    common_chaos_en,
    common_space_more,
    common_url_only,
    common_colon_end,
    common_check_photo,
    common_img_html_tag,
    common_special_character,
    common_enter_ratio_more,
    common_doc_repeat,
    common_word_stuck,
    common_no_punc,
    common_html_entity,
    common_invisible_char,
    common_bracket_unmatch,
]
zh_all = [
    common_enter_more,
    common_content_null,
    common_chaos_zh,
    common_space_more,
    common_url_only,
    common_colon_end,
    common_check_photo,
    common_img_html_tag,
    common_special_character,
    common_enter_ratio_more,
    common_doc_repeat,
    common_bracket_unmatch,
    common_html_entity,
    common_anti_crawler_zh,
    common_invisible_char,
    common_license_key,
    common_unconverted_symbol,
    common_special_mark,
    common_joint_special_symbol,
    common_underscore_length,
    common_ellipsis_ratio,
    common_invalid_web,
    common_emoj_characters,
]
arabic_all = [
    common_enter_more,
    common_content_null,
    common_space_more,
    common_url_only,
    common_colon_end,
    common_check_photo,
    common_img_html_tag,
    common_special_character,
    common_enter_ratio_more,
    common_doc_repeat,
    common_html_entity,
    common_invisible_char,
    common_bracket_unmatch,
]