
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-31T15:00:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f29e969920b45d63546178a04dbd2743958c6c5",
 "version": "1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
