
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-01T00:31:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9e451dd227f35e7adf11e858f0d1c874ec16f38",
 "version": "3.0.3.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
