from django.utils.translation import ugettext_lazy as _

DEFAULT_ITEM_TIME_BUFFER = 100
DEFAULT_PROCESS_SIZE = 2

IMPORT_SETUP_ITEM_STATE_NONE = 1
IMPORT_SETUP_ITEM_STATE_ERROR = 2
IMPORT_SETUP_ITEM_STATE_QUEUED = 3
IMPORT_SETUP_ITEM_STATE_PROCESSING = 6
IMPORT_SETUP_ITEM_STATE_PROCESSED = 7

IMPORT_SETUP_ITEM_STATE_CHOICES = (
    (IMPORT_SETUP_ITEM_STATE_ERROR, _(message='Error')),
    (IMPORT_SETUP_ITEM_STATE_NONE, _(message='None')),
    (IMPORT_SETUP_ITEM_STATE_PROCESSED, _(message='Processed')),
    (IMPORT_SETUP_ITEM_STATE_PROCESSING, _(message='Processing')),
    (IMPORT_SETUP_ITEM_STATE_QUEUED, _(message='Queued'))
)

IMPORT_SETUP_STATE_NONE = 1
IMPORT_SETUP_STATE_ERROR = 2
IMPORT_SETUP_STATE_POPULATING = 3
IMPORT_SETUP_STATE_POPULATED = 6
IMPORT_SETUP_STATE_PROCESSING = 7
IMPORT_SETUP_STATE_PROCESSED = 8

IMPORT_SETUP_STATE_CHOICES = (
    (IMPORT_SETUP_STATE_ERROR, _(message='Error')),
    (IMPORT_SETUP_STATE_NONE, _(message='None')),
    (IMPORT_SETUP_STATE_POPULATED, _(message='Populated')),
    (IMPORT_SETUP_STATE_POPULATING, _(message='Populating')),
    (IMPORT_SETUP_STATE_PROCESSED, _(message='Processed')),
    (IMPORT_SETUP_STATE_PROCESSING, _(message='Processing'))
)
