
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-30T14:33:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "40fe71e4e393b47e0a231b178add25696e469405",
 "version": "2022.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
