#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2403-24-gb887b5d7"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2403
#define NETGEN_VERSION_TWEAK 24
#define NETGEN_VERSION_HASH "gb887b5d7"
#endif // NETGEN_VERSION_HPP_INCLUDED
