
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-02T13:56:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "87e16d5a881cc730eaa2b216d040ab445495cac6",
 "version": "0.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
