# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego.models.client_template_creation import ClientTemplateCreation

class TestClientTemplateCreation(unittest.TestCase):
    """ClientTemplateCreation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientTemplateCreation:
        """Test ClientTemplateCreation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientTemplateCreation`
        """
        model = ClientTemplateCreation()
        if include_optional:
            return ClientTemplateCreation(
                name = '',
                template = ''
            )
        else:
            return ClientTemplateCreation(
                name = '',
                template = '',
        )
        """

    def testClientTemplateCreation(self):
        """Test ClientTemplateCreation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
