# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego.models.billing_plan import BillingPlan

class TestBillingPlan(unittest.TestCase):
    """BillingPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingPlan:
        """Test BillingPlan
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingPlan`
        """
        model = BillingPlan()
        if include_optional:
            return BillingPlan(
                plan = sweego.models.billing_plan_info_data.BillingPlanInfoData(
                    id = '', 
                    range_name = '', 
                    plan_name = '', 
                    price = 56, 
                    commitment = 'day', ),
                features = [
                    sweego.models.billing_plan_feature_data.BillingPlanFeatureData(
                        value = '', 
                        period = 'day', 
                        name = '', 
                        description = '', 
                        dbtype = 'integer', )
                    ]
            )
        else:
            return BillingPlan(
                plan = sweego.models.billing_plan_info_data.BillingPlanInfoData(
                    id = '', 
                    range_name = '', 
                    plan_name = '', 
                    price = 56, 
                    commitment = 'day', ),
                features = [
                    sweego.models.billing_plan_feature_data.BillingPlanFeatureData(
                        value = '', 
                        period = 'day', 
                        name = '', 
                        description = '', 
                        dbtype = 'integer', )
                    ],
        )
        """

    def testBillingPlan(self):
        """Test BillingPlan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
