# Autogenerated by devscripts/update-version.py

__version__ = '2024.05.30.232720'

RELEASE_GIT_HEAD = '2e5a47da400b645aadbda6afd1156bd89c744f48'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.05.30.232720dev'
