from pystyle import Colors

#blue_to_white = Colors.blue_to_white
#white_to_blue = Colors.white_to_blue

black_to_white = "m;m;m"
black_to_red = "m;0;0"
black_to_green = "0;m;0"
black_to_blue = "0;0;m"
white_to_black = "n;n;n"
white_to_red = "255;n;n"
white_to_green = "n;255;n"
white_to_blue = "n;n;255"
red_to_black = "n;0;0"
red_to_white = "255;m;m"
red_to_yellow = "255;m;0"
red_to_purple = "255;0;m"
green_to_black = "0;n;0"
green_to_white = "m;255;m"
green_to_yellow = "m;255;0"
green_to_cyan = "0;255;m"
blue_to_black = "0;0;n"
blue_to_white = "m;m;255"
blue_to_cyan = "0;m;255"
blue_to_purple = "m;0;255"
yellow_to_red = "255;n;0"
yellow_to_green = "n;255;0"
purple_to_red = "255;0;n"
purple_to_blue = "n;0;255"
cyan_to_green = "0;255;n"
cyan_to_blue = "0;n;255"