
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-02T14:51:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac1a1ed748a16d5362ea814a3a65ec0e3e7968d0",
 "version": "2024.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
