
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-30T17:51:13+0930",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c247bbb5baaefc483c668cc92efbccc3b014c9c",
 "version": "v0.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
