#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2403-23-ge4752243"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2403
#define NETGEN_VERSION_TWEAK 23
#define NETGEN_VERSION_HASH "ge4752243"
#endif // NETGEN_VERSION_HPP_INCLUDED
