
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-02T16:08:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ccc341fc420705b1f1447bd732f9084f160fc0e",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
