# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego_api.api.configuration_api import ConfigurationApi


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigurationApi()

    def tearDown(self) -> None:
        pass

    def test_get_config_config_project_type_get(self) -> None:
        """Test case for get_config_config_project_type_get

        Get config from a given channel
        """
        pass


if __name__ == '__main__':
    unittest.main()
