# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego_api.models.base_response1 import BaseResponse1

class TestBaseResponse1(unittest.TestCase):
    """BaseResponse1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseResponse1:
        """Test BaseResponse1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseResponse1`
        """
        model = BaseResponse1()
        if include_optional:
            return BaseResponse1(
                channel = '',
                client_id = '',
                error = [
                    ''
                    ],
                msg = '',
                msps = [
                    ''
                    ],
                nb_page = 56,
                nb_result = 56,
                nb_result_without_offset = 56,
                result = None,
                sms_types = [
                    ''
                    ],
                senders = [
                    ''
                    ],
                state = True
            )
        else:
            return BaseResponse1(
                state = True,
        )
        """

    def testBaseResponse1(self):
        """Test BaseResponse1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
