# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sweego_api.models.mbz_swg_pgsql_models_sweego_conf_client_client_type import MbzSwgPgsqlModelsSweegoConfClientClientType

class TestMbzSwgPgsqlModelsSweegoConfClientClientType(unittest.TestCase):
    """MbzSwgPgsqlModelsSweegoConfClientClientType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMbzSwgPgsqlModelsSweegoConfClientClientType(self):
        """Test MbzSwgPgsqlModelsSweegoConfClientClientType"""
        # inst = MbzSwgPgsqlModelsSweegoConfClientClientType()

if __name__ == '__main__':
    unittest.main()
