
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-30T09:32:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c70604468f141cd09e7129931e90dc739d1b1226",
 "version": "0.7.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
