# coding: utf-8

"""
    Sweego API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.6.5a
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InvoiceStatus(str, Enum):
    """
    Represents all different status of an invoice
    """

    """
    allowed enum values
    """
    DRAFT = 'draft'
    OPEN = 'open'
    TO_PAY = 'to_pay'
    GRACE_PERIOD = 'grace_period'
    PARTIALLY_PAID = 'partially_paid'
    PAID = 'paid'
    LATE = 'late'
    VOIDED = 'voided'
    CLOSED = 'closed'
    ERROR = 'error'
    MISSING_INFO = 'missing_info'
    ARCHIVED = 'archived'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InvoiceStatus from a JSON string"""
        return cls(json.loads(json_str))


