math_type = {
    "geometry": {
        "G2-PL": ["đa diện", "tứ diện"],
        "G2-S": ["hình cầu", "cầu", "mặt cầu"],
        "G2-P": ["khối chóp", "hình chóp"],
        "G2-CY": ["hình trụ", "lăng trụ"],
        "G2-CO": ["hình nón"],
        "G2-R": ["hộp chữ nhật"],
        "G2-CU": ["lập phương", "hlp"],
        "G3-V": [
            "vecto",
            "vector",
            "tọa độ",
            "Ox ; Oy ; Oz",
            "Oxy",
            "Oxyz",
            "phương trình tổng quát",
            "Tọa độ giao điểm",
            "chính tắc",
            "Parabol",
            "parabol",
        ],
        "G1-T": ["tam giác"],
        "G1-Q": ["tứ giác", "hình thang", "hình bình hành", "hình thoi"],
        "G1-P": ["đa giác"],
        "G1-C": ["hình tròn", "đường tròn"],
        "G1-R": ["chữ nhật", "HCN"],
        "G1-S": ["hình vuông"],
        "G1-L": ["trục đối xứng", "góc", "tia", "đoạn thẳng"],
    },
    "algebra": {
        "A-D": [
            "chia hết",
            "Xác định tính đúng đắn của mệnh đề",
            "số đối",
            "trục số",
            "phần nguyên",
            "phần thập phân",
            "tử số",
            "mẫu số",
            "số gần đúng",
            "sai số",
            "nghịch đảo",
            "thập phân hữu hạn",
            "vô hạn tuần hoàn",
            "Số lớn nhất có",
            "thích hợp điền",
            "số hữu tỉ",
        ],
        "A-EQ": [
            "Tìm nghiệm của phương trình",
            "tìm nghiệm",
            "nghiệm sao cho",
            "phương trình số phức",
            "tập xác định",
            "Phương trình",
            "Giải pt",
            "pt",
            "Giải phương trình",
            "giải phương trình",
            "phương trình",
            "nghiệm của phương trình",
            "Giải các phương trình",
            "Cho phương trình",
        ],
        "A-I": ["giải bất phương trình", "cho bất phương trình", " bất phương trình"],
        "A-SE": ["hệ phương trình"],
        "A-EX": [
            "Tính nhẩm",
            "biểu thức",
            "đa thức",
            "tính giá trị biểu thức",
            "so sánh",
            "làm tròn",
            "rút gọn biểu thức",
            "rút gọn",
            "quy đồng",
            "tối giản",
            "đa thức thành nhân tử",
            "tính chẵn, lẻ",
            "đơn thức",
            "tính nhanh",
            "Tính hợp lí",
            "Tính nhanh",
            "bằng cách thuận tiện",
            "Biểu thức",
        ],
        "A-C": ["số phức", "Số phức"],
        "A-S": ["tập hợp", "Tập hợp"],
        "A-SEQ": [
            "sắp xếp",
            "liền trước",
            "liền sau",
            "So lien truoc",
            "số lớn nhất",
            "bé nhất",
            "dãy số",
            "dãy số",
            "cấp số cộng",
            "cấp số nhân",
            "CSN",
            "CSC",
            "Un",
        ],
        "A-UB": ["tìm số tự nhiên", "ước chung", "bội chung", "BCNN", "UCLN", "ước của"],
        "A-P": ["khởi hành", "vận tốc", "thời gian"],
    },
    "counting_probability": {
        "SC-N": ["newton", "nhị thức", "nhị thức newton"],
        "SC-C": [
            "quy tắc đếm",
            "hoán vị",
            "chỉnh hợp",
            "tổ hợp",
            "xác suất",
            "chọn ngẫu nhiên",
            "Chọn ngẫu nhiên",
            "lập được bao nhiêu",
            "Xác suất",
            "đôi một",
            "lập được bao nhiêu số",
            "không gian mẫu",
            "bao nhiêu cách",
        ],
        "SC-S": [
            "mẫu số liệu",
            "đếm số lượng",
            "trung vị",
            "trung bình cộng",
            "khoảng tứ phân vị",
            "trong bảng",
            "phương sai",
        ],
    },
    "calculus": {
        "C-AN": ["nguyên hàm"],
        "C-D": ["đạo hàm", "vi phân", "số gia", "Đạo hàm", "dx"],
        "C-I": ["tích phân"],
        "C-L": ["liên tục", "giới hạn", "tính liên tục", "Lim", "lim"],
        "C-G": [
            "biến thiên",
            "cực trị",
            "phương trình tiếp tuyến",
            "PTTT",
            "tính chẵn lẻ",
            "đồ thị hàm số",
            "bảng biến thiên",
            "đồng biến",
            "nghịch biến",
            "Đồ thị hàm số",
            "thuộc đồ thị",
            "đồ thị",
            "cực đại",
            "cực tiểu",
        ],
        "C-AS": ["tiệm cận", "tiệm cận hàm số"],
    },
}
