from enum import Enum

KOZMO_OPERATION_HISTORY_DIRECTORY_DEFAULT = '.operation_history'
KOZMO_OPERATION_HISTORY_DIRECTORY_ENVIRONMENT_VARIABLE_NAME = 'KOZMO_OPERATION_HISTORY_DIRECTORY'


class ResourceType(str, Enum):
    PIPELINE = 'pipeline'
