from dataclasses import dataclass, field, fields


@dataclass(frozen=True)
class CONSTANT:
    INPUT = "INPUT"
    TRANSFORMED = "TRANSFORMED"
    OUTPUT_PLACEHOLDER = "OUTPUT_PLACEHOLDER"

    OUTPUT = "OUTPUT"

    PREPROCESSED_INPUT = "PREPROCESSED_INPUT"
    PREPROCESSED_TRANSFORMED = "PREPROCESSED_TRANSFORMED"
    PREPROCESSED_OUTPUT_PLACEHOLDER = "PREPROCESSED_OUTPUT_PLACEHOLDER"

    PCM_VERSION = "PCM_VERSION"
    VAP_PREPROCESSING_HOOKS = "VAP_PREPROCESSING_HOOKS"

    # TODO: how to make hierarchy
    # class CACHE_TYPE:
    #     INPUT = "INPUT"
    #     TRANSFORMED = "TRANSFORMED"
    #     OUTPUT = "OUTPUT"
    #     OUTPUT_PLACEHOLDER = "OUTPUT_PLACEHOLDER"
    #     PREPROCESSED_INPUT = "PREPROCESSED_INPUT"
    #     PREPROCESSED_TRANSFORMED = "PREPROCESSED_TRANSFORMED"
    #     PREPROCESSED_OUTPUT = "PREPROCESSED_OUTPUT"
