class NUIDStr:
    def as_str(self) -> str: ...

    def into_bytes(self) -> bytes: ...


class NUID:
    def next(self) -> NUIDStr: ...

    def randomize_prefix(self) -> None: ...

    def reset_sequential(self) -> None: ...
