# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geoip.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgeoip.proto\"\"\n\tGeoIPList\x12\x15\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x06.GeoIP\"\xe8\x01\n\x05GeoIP\x12\x19\n\x0c\x63ountry_code\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x04\x63idr\x18\x02 \x03(\x0b\x32\x05.CIDR\x12\x1a\n\rinverse_match\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12\x1a\n\rresource_hash\x18\x04 \x01(\x0cH\x02\x88\x01\x01\x12\x11\n\x04\x63ode\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x18\n\tfile_path\x18\xa0\x93\x04 \x01(\tH\x04\x88\x01\x01\x42\x0f\n\r_country_codeB\x10\n\x0e_inverse_matchB\x10\n\x0e_resource_hashB\x07\n\x05_codeB\x0c\n\n_file_path\"b\n\x04\x43IDR\x12\x0f\n\x02ip\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x13\n\x06prefix\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x16\n\x07ip_addr\x18\xa0\x93\x04 \x01(\tH\x02\x88\x01\x01\x42\x05\n\x03_ipB\t\n\x07_prefixB\n\n\x08_ip_addrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geoip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GEOIPLIST']._serialized_start=15
  _globals['_GEOIPLIST']._serialized_end=49
  _globals['_GEOIP']._serialized_start=52
  _globals['_GEOIP']._serialized_end=284
  _globals['_CIDR']._serialized_start=286
  _globals['_CIDR']._serialized_end=384
# @@protoc_insertion_point(module_scope)
