# coding: utf-8

"""
    vectorize.sh API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyvectorize.models.index_query_request_schema import IndexQueryRequestSchema

class TestIndexQueryRequestSchema(unittest.TestCase):
    """IndexQueryRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndexQueryRequestSchema:
        """Test IndexQueryRequestSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndexQueryRequestSchema`
        """
        model = IndexQueryRequestSchema()
        if include_optional:
            return IndexQueryRequestSchema(
                id = int_or_uuid,
                text = 'The quick brown fox jumps over the lazy dog'
            )
        else:
            return IndexQueryRequestSchema(
        )
        """

    def testIndexQueryRequestSchema(self):
        """Test IndexQueryRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
