# coding: utf-8

"""
    vectorize.sh API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyvectorize.models.index_upsert_request_schema_id import IndexUpsertRequestSchemaId

class TestIndexUpsertRequestSchemaId(unittest.TestCase):
    """IndexUpsertRequestSchemaId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndexUpsertRequestSchemaId:
        """Test IndexUpsertRequestSchemaId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndexUpsertRequestSchemaId`
        """
        model = IndexUpsertRequestSchemaId()
        if include_optional:
            return IndexUpsertRequestSchemaId(
            )
        else:
            return IndexUpsertRequestSchemaId(
        )
        """

    def testIndexUpsertRequestSchemaId(self):
        """Test IndexUpsertRequestSchemaId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
