
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-29T11:03:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4c74bf1b12f92ec02fc8112c20970c941146a27",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
